#ifndef CORE_OPTIMIZER_LBFGS_SEARCH_POLICIES_LINE_SEARCH_BACKTRACKING_HPP
#define CORE_OPTIMIZER_LBFGS_SEARCH_POLICIES_LINE_SEARCH_BACKTRACKING_HPP

namespace openml {
namespace optimizer {

template <typename DataType>
class LineSearchBacktracking {




};

}
}

#endif /* CORE_OPTIMIZER_LBFGS_SEARCH_POLICIES_LINE_SEARCH_BACKTRACKING_HPP */