#ifndef CORE_OPTIMIZER_LBFGS_SEARCH_POLICIES_LINE_SEARCH_BRACKETING_HPP
#define CORE_OPTIMIZER_LBFGS_SEARCH_POLICIES_LINE_SEARCH_BRACKETING_HPP

namespace openml {
namespace optimizer {

template <typename DataType>
class LineSearchBracketing {




};

}
}

#endif /* CORE_OPTIMIZER_LBFGS_SEARCH_POLICIES_LINE_SEARCH_BRACKETING_HPP */